before_script:
    - "apt-get update -qy"
    - "apt-get install -y python3-dev python3-pip"
    - "pip3 install -r requirements.txt"

job_tests:
    image: python:3.5.2
    stage: test
    script:
        - "pip3 install -r requirements.txt"
        - "nosetests --with-coverage --cover-package=aschedule"
